# Noctalia Theme for Mango
# Generated automatically by Noctalia

rootcolor = 0x101418ff
bordercolor = 0x8c9199ff
dropcolor = 0x9ccbfb80
splitcolor = 0xd4bee6ff
focuscolor = 0x9ccbfbff
maximizescreencolor = 0xb9c8daff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xd4bee6ff
globalcolor = 0x114a73ff
overlaycolor = 0x3a4857ff
jump_label_decorate_fg_color = 0xe0e2e8ff
jump_label_decorate_bg_color = 0x272a2fff
jump_label_decorate_focus_fg_color = 0x003354ff
jump_label_decorate_focus_bg_color = 0x9ccbfbff
jump_label_decorate_border_color = 0x8c9199ff
group_bar_decorate_fg_color = 0xe0e2e8ff
group_bar_decorate_bg_color = 0x272a2fff
group_bar_decorate_focus_fg_color = 0x003354ff
group_bar_decorate_focus_bg_color = 0x9ccbfbff
group_bar_decorate_border_color = 0x8c9199ff
