"$schema" = 'https://starship.rs/config-schema.json'

format = """
[ ](bg20)\
$os\
$username\
[](bg:bg30 fg:bg20)\
$hostname\
[](bg:bg40 fg:bg30)\
$directory\
[](bg:bg50 fg:bg40)\
$git_branch\
$git_status\
[](bg:bg60 fg:bg50)\
$c\
$cpp\
$rust\
$ruby\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$lua\
$bun\
$zig\
[](bg:bg70 fg:bg60)\
$docker_context\
$conda\
$pixi\
[ ](fg:bg70)\
"""

palette = 'matugen'

[palettes.matugen]
bg0 = '{{ palettes.primary._0.hex }}'
bg5 = '{{ palettes.primary._5.hex }}'
bg10 = '{{ palettes.primary._10.hex }}'
bg15 = '{{ palettes.primary._15.hex }}'
bg20 = '{{ palettes.primary._20.hex }}'
bg25 = '{{ palettes.primary._25.hex }}'
bg30 = '{{ palettes.primary._30.hex }}'
bg35 = '{{ palettes.primary._35.hex }}'
bg40 = '{{ palettes.primary._40.hex }}'
bg50 = '{{ palettes.primary._50.hex }}'
bg60 = '{{ palettes.primary._60.hex }}'
bg70 = '{{ palettes.primary._70.hex }}'
bg80 = '{{ palettes.primary._80.hex }}'
bg90 = '{{ palettes.primary._90.hex }}'
bg100 = '{{ palettes.primary._100.hex }}'
fg1 = '{{ colors.on_surface.default.hex }}'

[palettes.kanso_zen]
color_fg0 = '#FFFFFF'
color_fg1 = '#C5C9C7'
color_bg1 = '#090E13'
color_red =  '#E46876'
color_orange = '#b98d7b'
color_yellow = '#E6C384'
color_green = '#87a987'
color_aqua = '#7AA89F'
color_blue = '#7FB4CA'
color_purple = '#938AA9'

[palettes.catppuccin_mocha]
color_bg1 = '#CDD6F4'
color_fg1 = '#11111b'
color_red =  '#F38BA8'
color_orange = '#FAB367'
color_yellow = '#F9E2AF'
color_green = '#A6E3A1'
color_aqua = '#94E2D5'
color_blue = '#74C7EC'
color_purple = '#B4BEFE'

[os]
disabled = false
style = "bg:bg20 fg:fg1"
format = "[$symbol ]($style)"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
CachyOS = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:bg20 fg:fg1"
style_root = "bg:bg20 fg:fg1"
format = '[$user ]($style)'

[hostname]
disabled = false
ssh_only = false
style = "bg:bg30 fg:fg1"
format = "[$ssh_symbol]($style)[$hostname]($style)"

[directory]
style = "bg:bg40 fg:fg1"
format = "[$path]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Desktop" = " "
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Videos" = " "
"Developer" = "󰲋 "
"Games" = "󰊖 "

[git_branch]
symbol = ""
style = "bg:bg50 fg:fg1"
format = '[$symbol $branch]($style)'

[git_status]
style = "bg:bg50 fg:fg1"
format = '[$all_status$ahead_behind]($style)'

[nodejs]
symbol = ""
style = "fg:fg1 bg:bg60"
format = '[$symbol $version]($style)'

[bun]
symbol = ""
style = "fg:fg1 bg:bg60"
format = '[$symbol $version]($style)'

[lua]
symbol = "󰢱"
style = "fg:fg1 bg:bg60"
format = '[$symbol $version]($style)'

[c]
symbol = ""
style = "fg:fg1 bg:bg60"
format = '[$symbol $version]($style)'

[cpp]
symbol = ""
style = "fg:fg1 bg:bg60"
format = '[$symbol $version]($style)'

[rust]
symbol = ""
style = "fg:fg1 bg:bg60"
format = '[$symbol $version]($style)'

[golang]
symbol = ""
style = "fg:fg1 bg:bg60"
format = '[$symbol $version]($style)'

[php]
symbol = ""
style = "fg:fg1 bg:bg60"
format = '[$symbol $version]($style)'

[java]
symbol = ""
style = "fg:fg1 bg:bg60"
format = '[$symbol $version]($style)'

[kotlin]
symbol = ""
style = "fg:fg1 bg:bg60"
format = '[$symbol $version]($style)'

[haskell]
symbol = ""
style = "fg:fg1 bg:bg60"
format = '[$symbol $version]($style)'

[python]
symbol = ""
style = "fg:fg1 bg:bg60"
format = '[$symbol $version]($style)'

[docker_context]
symbol = ""
style = "fg:fg1 bg:bg70"
format = '[$symbol($context)]($style)'

[conda]
style = "fg:fg1 bg:bg70"
format = '[$symbol($environment)]($style)'

[pixi]
style = "fg:fg1 bg:bg70"
format = '[$symbol($version)($environment)]($style)'

[status]
disabled = false
success_symbol = '✅'
style = 'fg:fg1 bg:bg80'
format = '[$symbol$status]($style)'

[cmd_duration]
disabled = false
style = 'fg:fg1 bg:bg80'
format = '[󰚭 $duration]($style)'
show_notifications = false

[time]
disabled = false
time_format = "%R"
style = "fg:fg1 bg:bg80"
format = '[ $time]($style)'

[line_break]
disabled = false
