[[mgr.prepend_keymap]]
on = ["R","b"]
run = "plugin recycle-bin"
desc = "Open Recycle Bin menu"

[[mgr.prepend_keymap]]
on = ["c","m"]
run = "plugin chmod"
desc = "Chmod on selected files"

## Dropping to the shell
# Linux
[[mgr.prepend_keymap]]
on   = "!"
for  = "unix"
run  = 'shell "$SHELL" --block'
desc = "Open $SHELL here"

# Windows
[[mgr.prepend_keymap]]
on   = "!"
for  = "windows"
run  = 'shell "powershell.exe" --block'
desc = "Open PowerShell here"

